FROM dockerhub.stensalinc.com/i386/cs50-baseline:latest
LABEL Maintainer1="Ning <ning@stensalinc.com>"

#RUN apk add --no-cache lsof
#RUN sudo apt-get install -y vim net-tools


USER root
RUN cp /usr/bin/nice /bin/nice

RUN rm -rf /sjacket/etc/ld-musl-i386.path \
    && rm -rf /sjacket/etc/abuild.conf \
    && rm -rf /sjacket/etc/abuild.conf.orig \
    && rm -rf /sjacket/etc/apk \
    && rm -rf /sjacket/apk \
    && rm -rf /sjacket/lib/apk

RUN rm -f /sjacket/stensal/bin/klaram.exe \
    && rm -f /sjacket/stensal/bin/clang-3.5 \
    && rm -f /sjacket/stensal/bin/stensal-nm \
    && rm -f /sjacket/stensal/bin/license.json

EXPOSE 7681

COPY run_in_cattlegrid.sh  /bin/run_in_cattlegrid.sh
COPY gdb.sh /bin/gdb.sh

COPY prlimit     /bin/prlimit
COPY ttyd  /bin/ishell
COPY dumb-init /bin/
COPY start.sh /bin

# All executables exposed to ishell
# should be located in /xshell
RUN mkdir -p /xshell/bin \
    && cp /bin/sh   /xshell/bin \
    && cp /usr/bin/env /xshell/bin \
    && cp /bin/bash /xshell/bin \
    && cp /bin/ls   /xshell/bin \
    && cp /bin/rm   /xshell/bin \
    && cp /bin/mv   /xshell/bin \
    && cp /usr/bin/clear /xshell/bin \
    && cp /bin/more /xshell/bin \
    && cp /usr/bin/git /xshell/bin 

COPY run_prog.sh /xshell/bin/
COPY greeting.sh /xshell/bin/
COPY ck.sh /xshell/bin/
COPY entrypoint.sh /bin/
RUN chmod -R -w /xshell/bin/


RUN chmod -w /xshell/bin /lib /usr/lib /usr/share
RUN groupadd -g 20000 tester
RUN useradd --shell /xshell/bin/sh --home-dir /home/jail tester -u 2000 -g tester

RUN apt-get remove -y wget curl \
    && rm /usr/bin/sudo \
    && rm /usr/bin/scp 

COPY cattlegrid_cs50  /bin/cattlegrid
COPY sh_in_cattlegrid_cs50.sh  /bin/sh_in_cattlegrid.sh

ENTRYPOINT ["/bin/dumb-init", "-c", "--", "/bin/entrypoint.sh"]
