FROM dockerhub.stensalinc.com/i386/cs50-baseline:latest
LABEL Maintainer1="Ning <ning@stensalinc.com>"

#RUN apk add --no-cache lsof
#RUN sudo apt-get install -y vim net-tools


USER root
RUN cp /usr/bin/nice /bin/nice

RUN rm -rf /sjacket/etc/ld-musl-i386.path \
    && rm -rf /sjacket/etc/abuild.conf \
    && rm -rf /sjacket/etc/abuild.conf.orig \
    && rm -rf /sjacket/etc/apk \
    && rm -rf /sjacket/apk \
    && rm -rf /sjacket/lib/apk

RUN rm -f /sjacket/stensal/bin/klaram.exe \
    && rm -f /sjacket/stensal/bin/clang-3.5 \
    && rm -f /sjacket/stensal/bin/stensal-nm \
    && rm -f /sjacket/stensal/bin/license.json

RUN apt-get remove -y wget curl \
    && rm /usr/bin/sudo \
    && rm /usr/bin/scp

RUN apt-get install -y libedit-dev \
    && apt-get install -y autotools-dev \
    && apt-get install -y automake
    
COPY dash-0.5.10.2.tar.gz /tmp
RUN cd /tmp \
    && tar -xf dash-0.5.10.2.tar.gz \
    && cd dash-0.5.10.2 \
    && ./autogen.sh \
    && ./configure --with-libedit \
    && make \
    && make install

RUN apt-get install -y apt-utils
RUN apt-get install -y software-properties-common

#RUN apt-get update \
#    && add-apt-repository ppa:cs50/ppa \
#    && apt-get update \
#    && apt-get install -y astyle

EXPOSE 7681

COPY prlimit    /sbin/prlimit
COPY ttyd       /sbin/ishell
COPY dumb-init  /sbin/
COPY start.sh   /sbin

# All executables exposed to ishell
# should be located in /xshell
RUN mkdir -p /xshell/bin \
    && cp /usr/local/bin/dash /xshell/bin \
    && cp /usr/bin/env        /xshell/bin \
    && cp /bin/bash           /xshell/bin \
    && cp /bin/ls             /xshell/bin \
    && cp /bin/rm             /xshell/bin \
    && cp /bin/rmdir          /xshell/bin \
    && cp /bin/mkdir          /xshell/bin \
    && cp /bin/mv             /xshell/bin \
    && cp /usr/bin/clear      /xshell/bin \
    && cp /bin/more /xshell/bin \
    && cp /usr/bin/git /xshell/bin \
    && cp /usr/bin/id  /xshell/bin \
    && cp /usr/bin/ssh  /xshell/bin

RUN mkdir -p /sbin \
    && mv /bin/sys* /sbin \
    && mv /bin/mknod /sbin \
    && mv /bin/mktemp /sbin \
    && mv /bin/ip     /sbin \
    && mv /bin/chgrp /sbin \
    && mv /bin/chmod /sbin \
    && mv /bin/chown /sbin \
    && mv /bin/journalctl /sbin \
    && mv /bin/kill /sbin \
    && mv /bin/mountpoint /sbin \
    && mv /bin/ps /sbin \
    && mv /bin/networkctl /sbin \
    && mv /bin/findmnt /sbin \
    && mv /bin/login* /sbin \
    && mv /bin/ss /sbin \
    && mv /bin/stty /sbin \
    && mv /bin/sync /sbin \
    && mv /bin/dd /sbin \
    && mv /bin/dumb-init /sbin \
    && mv /bin/fuser /sbin \
    && mv /bin/df /sbin \
    && mv /bin/dmesg /sbin \
    && mv /bin/wdctl /sbin \
    && mv /bin/su    /sbin \
    && mv /bin/umount /sbin \
    && mv /bin/mount  /sbin \
    && mv /bin/ping   /sbin
    

COPY run_prog.sh /bin/
COPY greeting_cs50.sh /xshell/bin/greeting.sh
COPY mybash.sh   /xshell/bin/
COPY ck.sh /xshell/bin/
COPY t1.sh /xshell/bin/
COPY t2.sh /xshell/bin/
COPY t3.sh /xshell/bin/
RUN chmod -R -w /xshell/bin/
RUN chmod -R -w /bin/


RUN chmod -w /xshell/bin /lib /usr/lib /usr/share
RUN groupadd -g 20000 tester
RUN useradd --shell /xshell/bin/sh --home-dir /home/jail tester -u 2000 -g tester


COPY entrypoint.sh             /sbin/
COPY cattlegrid_cs50           /sbin/cattlegrid
COPY sh_in_cattlegrid_cs50.sh  /sbin/sh_in_cattlegrid.sh

ENTRYPOINT ["/sbin/dumb-init", "-c", "--", "/sbin/entrypoint.sh"]
